### ISSUE TITLE
シリアルのポートを自動認識して、一々修正しなくてもいいようにする

### ISSUE THREAD

**Issue by KorRyu3** [TechC-SugarCane/ImageRecognitionWinApp#61]
[参考]
https://firtel.blogspot.com/2021/08/pyserial-port-info.html
これとか便利かも     (今回の回路　VID= 0x0483, PID = 0x5740)

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modify the execute_nozzle function to automatically detect the correct serial port using the device's VID and PID. This change will make the application more robust and user-friendly by eliminating the need for hardcoding the COM port.

You can review changes in this commit: https://github.com/lattaai13/TechC-SugarCane-ImageRecognitionWinApp-61/commit/9f59e515d634c6bcd1149d3c7316582255ed5936.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
